.TH TRACEMERGE "1" "October 2006" "tracereport (libtrace)" "User Commands"
.SH NAME
tracereport \- Report summary statistics on a trace
.SH SYNOPSIS
.B tracereport 
inputuri...
.SH DESCRPTION
tracereport lists various summary statistics about a trace.

The sections are:
.IP \(bu 4 
Errors
.IP \(bu 4
Flows
.IP \(bu 4
Type of Service
.IP \(bu 4
Protocol breakdown
.IP \(bu 4
Port breakdown
.IP \(bu 4
TTL breakdown
.IP \(bu 4
Direction

.SH SEE ALSO
libtrace(3), tracemerge(1), tracesplit(1), tracesplit_dir(1), tracefilter(1),
traceconvert(1), tracestats(1), tracertstats(1), tracereport(1), tracedump(1),
traceanon(1), tracesummary(1)

.SH AUTHORS
Perry Lorier <perry@cs.waikato.ac.nz>
