#define PACKAGE_VERSION "3.0.0"

#define HAVE__STRNICMP 1

#define HAVE_SPRINTF_S 1

#define HAVE_PCAP 1
#define HAVE_BPF 1
#define HAVE_PCAP_BPF 1
#define HAVE_PCAP_H 1
#define HAVE_PCAP_SENDPACKET 1
