.TH TRACEFILTER "1" "October 2005" "tracefilter (libtrace)" "User Commands"
.SH NAME
tracefilter \- apply a bpf filter to a trace
.SH SYNOPSIS
.B tracefilter 
inputuri bpf outputuri ...
.SH DESCRPTION
tracefilter copies all packets that match a bpf expression to an output file.

tracefilter is a shellscript wrapper around tracesplit(1)

.SH LINKS
More details about tracefilter (and libtrace) can be found at
http://www.wand.net.nz/trac/libtrace/wiki/UserDocumentation

.SH SEE ALSO
libtrace(3), tracemerge(1), tracesplit(1), tracesplit_dir(1), traceconvert(1),
tracereport(1), tracestats(1), tracertstats(1), tracepktdump(1), traceanon(1), 
tracesummary(1), tracereplay(1), tracediff(1), traceends(1), tracetopends(1)

.SH AUTHORS
Perry Lorier <perry@cs.waikato.ac.nz>
