.TH TRACETOP "1" "March 2009" "tracetop (libtrace)" "User Commands"
.SH NAME
tracetop \- show top flows
.SH SYNOPSIS
.B tracetop
[ \fB-f \fRbpf | \fB--filter=\fRbpf]
[ \fB-s \fRsnaplen | \fB--snaplen=\fRsnaplen]
[ \fB-p \fRpromisc | \fB--promisc=\fRpromisc]
[ \fB--bits-per-sec ]
[ \fB--percent ]
[ \fB--wide | -w ]
[ \fB-i \fRinterval | \fB--interval=\fRinterval]
[ \fB-h \fR| \fB--help\fR]
[ \fB-H \fR| \fB--libtrace-help\fR]
inputuri ...
.SH DESCRIPTION
tracetop shows the top 'n' flows every second
.TP
\fB\-f\fR bpf filter
Count only packets that match tcpdump style bpf filter

.TP
\fB\-i\fR interval
Wait interval seconds between updates.  (default 2).

.TP
\fB\-\-wide
Expand the display to be able to fit IPv6 addresses. Use this to ensure the
formatting lines up in the presence of IPv6 traffic.

.TP
\fB\-\-percent\fR 
Display flow bytes and packets as a percentage of total traffic

.TP
\fB\-\-bits\-per\-second\fR 
Display flow bandwidth as the number of bits per second.

.SH LINKS
More details about tracetop (and libtrace) can be found at
http://www.wand.net.nz/trac/libtrace/wiki/UserDocumentation

.SH SEE ALSO
libtrace(3), tracemerge(1), tracefilter(1), traceconvert(1), tracesplit_dir(1),
tracereport(1), tracertstats(1), tracestats(1), tracepktdump(1), traceanon(1),
tracesummary(1), tracereplay(1), tracediff(1), traceends(1), tracetopends(1)

.SH AUTHORS
Perry Lorier <perry@cs.waikato.ac.nz>
