.TH TRACEMERGE "1" "March 2006" "tracemerge (libtrace)" "User Commands"
.SH NAME
tracemerge \- Merge one (or more) traces together
.SH SYNOPSIS
.B tracemerge 
[ \-i | \-\^\-set-interface ]
[ \-u | \-\^\-unique-packets ]
outputuri inputuri...
.SH DESCRPTION
tracemerge merges two or more traces together, keeping packets in order.

.TP
.PD 0
.BI \-i
.TP
.PD
.BI \-\^\-set-interface
replace the "interface" bits in the erf header (or the "direction" bit in
other trace files) to be 0 for the first file, 1 for the second file etc.

.TP
.PD 0
.BI \-u
.TP
.PD
.BI \-\^\-unique-packets
Ignore duplicate packets with identical timestamps.

.SH SEE ALSO
libtrace(3), tracesplit(1), tracesplit_dir(1), tracefilter(1),
traceconvert(1), tracereport(1), tracertstats(1), tracestats(1), tracedump(1),
traceanon(1), tracesummary(1)

.SH AUTHORS
Perry Lorier <perry@cs.waikato.ac.nz>
