#!/bin/sh

if [ $# -lt 1 ]; then
	echo usage: $0 inputuri...
fi

exec tracestats --filter 'not ether proto \ip and not ether proto 0x86dd' \
		--filter 'ether proto 0x86dd' \
		--filter 'ether proto \ip' \
		--filter tcp \
		--filter udp \
		--filter icmp \
		--filter 'not (tcp or udp or icmp)' \
		--filter 'tcp and port http or https' \
		--filter 'tcp and port smtp' \
		--filter 'tcp and port pop3 or pop3s' \
		--filter 'tcp and port imap or imaps' \
		--filter 'port domain' \
		--filter 'icmp[icmptype]=icmp-echoreply' \
		"$@"
