name: CI

on: [pull_request]
jobs:
  clang-format:
    name: Clang Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install clang-format
      run: sudo apt-get install clang-format
    - name: Download git-clang-format
      run: wget https://raw.githubusercontent.com/llvm-mirror/clang/master/tools/clang-format/git-clang-format
    - name: Install git-clang-format
      run: sudo install -t /bin git-clang-format
    - name: Fetch origin ${{ github.base_ref }}
      run: git fetch --no-tags --prune --depth=1 origin ${{ github.base_ref }}
    - name: clang-format
      run: git clang-format origin/${{ github.base_ref }}
    - name: diff
      run: git diff --exit-code
  run-tests-ubuntu:
    name: Run Tests - Ubuntu 20.04
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install Dependencies
      run: sudo apt-get install flex bison libpcap0.8-dev libtool autoconf automake m4 gcc clang llvm gcc-multilib libelf-dev git
    - name: Build/Install Wandio
      run: |
        cd wandio
        ./bootstrap.sh
        ./configure
        make
        sudo make install
        sudo ldconfig
    - name: Build/Install Libbpf
      run: |
        git clone https://github.com/libbpf/libbpf
        cd libbpf/src
        make
        sudo make install
        echo "/usr/lib64" | sudo tee -a /etc/ld.so.conf.d/lib64.conf
        sudo ldconfig
    - name: Build/Install Libtrace
      run: |
        ./bootstrap.sh
        ./configure
        make
        sudo make install
    - name: Build Tests
      run: cd test; make address-san
    - name: Run do-tests.sh
      run: cd test; ./do-tests.sh
    - name: Run do-tests-parallel.sh
      run: cd test; ./do-tests-parallel.sh
    - name: Run do-tests-datastruct.sh
      run: cd test; ./do-tests-datastruct.sh
    - name: Run do-live-tests.sh
      run: cd test; sudo ./do-live-tests.sh
  run-tests-macos:
    name: Run Tests - MacOS Catalina 10.15
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install Dependencies
      run: |
        brew install flex bison libpcap libtool autoconf automake m4 gcc
    - name: Build/Install Wandio
      run: |
        cd wandio
        ./bootstrap.sh
        ./configure
        make
        sudo make install
    - name: Build/Install Libtrace
      run: |
        ./bootstrap.sh
        ./configure
        make
        sudo make install
    - name: Build Tests
      run: cd test; make
    - name: Run do-tests.sh
      run: cd test; ./do-tests.sh
    - name: Run do-tests-parallel.sh
      run: cd test; ./do-tests-parallel.sh
    - name: Run do-tests-datastruct.sh
      run: cd test; ./do-tests-datastruct.sh
